// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Task_Frank_db.Models;

namespace Task_Frank_db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211125133703_temp2")]
    partial class temp2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Task_Frank_db.Models.Address", b =>
                {
                    b.Property<string>("Town")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("varchar(25)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .HasColumnType("varchar(25)");

                    b.HasKey("Town");

                    b.HasIndex("PersonID")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Task_Frank_db.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Task_Frank_db.Models.Address", b =>
                {
                    b.HasOne("Task_Frank_db.Models.Person", "Person")
                        .WithOne("Address")
                        .HasForeignKey("Task_Frank_db.Models.Address", "PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Task_Frank_db.Models.Person", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
